__ct__14JKRCompArchiveFlQ210JKRArchive15EMountDirection
__dt__14JKRCompArchiveFv
open__14JKRCompArchiveFl
fetchResource__14JKRCompArchiveFPQ210JKRArchive12SDIFileEntryPUl
fetchResource__14JKRCompArchiveFPvUlPQ210JKRArchive12SDIFileEntryPUl15JKRExpandSwitch
removeResourceAll__14JKRCompArchiveFv
removeResource__14JKRCompArchiveFPv