menuSelectOption__17TitleSetupSectionFR4Menu
message__20TitlesMovieInterfaceFii
init__13TitlesSectionFv
update__17TitleSetupSectionFv
draw__17TitleSetupSectionFR8Graphics
drawMenu__17TitleSetupSectionFR8GraphicsP4Menuf
invoke__37Delegate1<17TitleSetupSection,R4Menu>FR4Menu