.text
.text
aAL_actor_ct(int something1, int something2) {
	
}

aAL_actor_dt
aAL_title_game_data_init_start_select
aAL_title_decide_p_sel_npc
aAL_wipe_end_check
aAL_chk_start_key
aAL_chk_start_key2
aAL_logo_in
aAL_back_fadein
aAL_start_key_chk_start_wait
aAL_game_start_wait
aAL_fade_out_start_wait
aAL_logo_in_init
aAL_back_fadein_init
aAL_start_key_chk_start_wait_init
aAL_fade_out_start_wait_init
aAL_setupAction
aAL_actor_move
aAL_copyright_draw
aAL_tm_draw
aAL_back_draw
aAL_press_start_draw
aAL_skl_draw
aAL_title_draw
aAL_actor_draw
.text
flash_rom_and_player_info_clear
decide_next_scene_no
title_action_data_init_start_select
.rodata
@470
@543
@544
@545
@546
@547
@548
@560
@561
@562
init_proc$578
draw_pos_x$591
draw_pos_y$592
init_disp$625
@644
@645
@646
init_disp$650
@669
@670
draw_pos_x$674
draw_pos_y$675
ps_prim_r$676
ps_prim_g$677
ps_prim_b$678
ps_env_r$679
ps_env_g$680
ps_env_b$681
init_disp$733
.data
Animal_Logo_Profile
process$579