__ct__13JKRDvdArchiveFlQ210JKRArchive15EMountDirection
__dt__13JKRDvdArchiveFv
open__13JKRDvdArchiveFl
fetchResource__13JKRDvdArchiveFPQ210JKRArchive12SDIFileEntryPUl
fetchResource__13JKRDvdArchiveFPvUlPQ210JKRArchive12SDIFileEntryPUl15JKRExpandSwitch
fetchResource_subroutine__13JKRDvdArchiveFlUlUlPUcUlii
fetchResource_subroutine__13JKRDvdArchiveFlUlUlP7JKRHeapiiPPUc